preload = ~/Wallpapers/yhwach.jpg
preload = ~/Wallpapers/shinsui.jpg
preload = ~/Wallpapers/skhand.jpg
preload = ~/Wallpapers/ichigo.jpg
preload = ~/Wallpapers/zaraki.jpg
preload = ~/Wallpapers/mountain.png

wallpaper = DP-2, ~/Wallpapers/yhwach.jpg
wallpaper = DP-3, ~/Wallpapers/mountain.png
