preload = ~/Wallpapers/yhwach.jpg
preload = ~/Wallpapers/shinsui.jpg
preload = ~/Wallpapers/skhand.jpg
preload = ~/Wallpapers/ichigo.jpg
preload = ~/Wallpapers/zaraki.jpg
preload = ~/Wallpapers/mountain.png

wallpaper {
	monitor = DP-2
	path = ~/Wallpapers/yhwach.jpg
}

wallpaper {
	monitor = DP-3
	path =  ~/Wallpapers/mountain.png
}

splash = false
